### ISSUE TITLE
Placeholders: use select mode 

### ISSUE THREAD

**Issue by clason** [norcalli/snippets.nvim#3]
When UltiSnips jumps to a placeholder with optional text (`${1:foo}`), the text is selected in select mode (`:h select-mode`); this way one can just start typing to replace the placeholder text (or deleting by pressing backspace). 

(Feel free to close or mark as `later` if this requires or is much easier with extmarks.)

**Comment by norcalli** [comment]
I now have two examples of different "inserters" as I call them, which are the visual part of how to actually execute the snippets.

If anyone wants to take a stab at trying this out before I get to it, feel free to check the `lua/snippets/inserters` directory and try it out.

**Comment by salkin-mada** [comment]
@clason to get this behavior (ish) i use these mappings:

```lua
function M.snippets()
    local opts = { noremap = true }
    api.nvim_set_keymap('i', '<A-k>', '<cmd>lua return require"snippets".expand_or_advance(1)<CR><ESC>gH', opts)
    api.nvim_set_keymap('i', '<A-j>', '<cmd>lua return require"snippets".advance_snippet(-1)<CR><ESC>gH', opts)
    api.nvim_set_keymap('n', '<A-k>', '<cmd>lua return require"snippets".expand_or_advance(1)<CR>gH', opts)
    api.nvim_set_keymap('n', '<A-j>', '<cmd>lua return require"snippets".advance_snippet(-1)<CR>gH', opts)
    api.nvim_set_keymap('s', '<A-k>', '<cmd>lua return require"snippets".expand_or_advance(1)<CR><ESC>gH', opts)
    api.nvim_set_keymap('s', '<A-j>', '<cmd>lua return require"snippets".advance_snippet(-1)<CR><ESC>gH', opts)
end
```
