### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by tjdevries** [norcalli/snippets.nvim#7]
Had a thought (not sure if this is how other snippet plugins do it) but you could call `indentexpr` maybe to see what the next indent should be on new lines? not sure if that would work though.

Leaving it here in case it's helpful (close if not)

**Comment by Shougo** [comment]
I think the example is needed.

**Comment by tjdevries** [comment]
Ah, I see. It doesn't actually require people to pass in the line number, as it is set to a `v` variable...

I was thinking that when expanding something and encountering `\n` character, you could insert the first line of the text, then call `indentexpr` to see what the indent of the next line would be.

I don't know if I have a good example, but basically I have an `it` expansion for lua to add `it('$1', function()\n$0\nend)` but the new lines don't indent to the right places (but they do when I hit enter)

**Comment by Shougo** [comment]
I get it.
I think tab character conversion is better like other snippet plugins.

`it('$1', function()\n\t$0\nend)`

Note: neosnippet implements the auto indentation feature by indent plugins.
But some indentation plugins are broken(PHP, python, etc...).

**Comment by clason** [comment]
From Gitter (copying here so it's preserved and more visible/searchable): you can now do 
```lua
local match_indentation = require'snippets.utils'.match_indentation
```
and then apply it to a snippet like so
```lua
["for"] = match_indentation "for ${1:i} = 0, $2 do\n  $0\nend",
```

**Comment by norcalli** [comment]
What he said.

It's also available in `require'snippets'.u` as an alias for "snippets.utils"

**Comment by norcalli** [comment]
It also includes a general utility in case you don't like the one I made for prefixing new lines.
